services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_USER_PASSWORD}
      POSTGRES_DB: ${DEVELOPMENT_DATABASE_NAME}  # OK for development and demo projects :)
    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: always

  python-app:
    build: .
    container_name: python_app
    ports:
      - "${APP_PORT_LOCAL}:5000"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
